In [1]:
import numpy as np
    
a = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
l = np.zeros(9)
l = l.reshape(3,3)

In [2]:
def choleskydecomp3(a):
    
    l[0][0] = np.sqrt(a[0][0])
    
    l[1][0] = a[0][1]/l[0][0]
    l[2][0] = a[0][2]/l[0][0]
    
    l[1][1] = np.sqrt(a[1][1]-l[1][0]**2)
    
    l[2][1] = (a[1][2]-l[1][0]*l[2][0])/l[1][1]
    
    l[2][2] = np.sqrt(a[2][2]-l[2][0]**2-l[2][1]**2)
    
    return l

In [3]:
l = choleskydecomp3(a)
print ("L = ",l)

L =  [[ 1.41421356  0.          0.        ]
 [-0.70710678  1.22474487  0.        ]
 [ 0.         -0.81649658  1.15470054]]


In [9]:
import scipy.linalg

a = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])

l = scipy.linalg.cholesky(a,lower=True)

print ("L = ",l)

L =  [[ 1.41421356  0.          0.        ]
 [-0.70710678  1.22474487  0.        ]
 [ 0.         -0.81649658  1.15470054]]


In [4]:
a = np.array([[4,1,1,1],[1,3,-1,-1],[1,-1,2,0],[1,1,0,2]])
l = np.zeros(16)
l = l.reshape(4,4)

In [5]:
def choleskydecomp4(a):
    
    l[0][0] = np.sqrt(a[0][0])
    
    l[1][0] = a[0][1]/l[0][0]
    l[2][0] = a[0][2]/l[0][0]
    l[3][0] = a[0][3]/l[0][0]
    
    l[1][1] = np.sqrt(a[1][1]-l[1][0]**2)
    
    l[2][1] = (a[2][1]-l[1][0]*l[2][0])/l[1][1]
    l[3][1] = (a[3][1]-l[1][0]*l[3][0])/l[1][1]
    
    l[2][2] = np.sqrt(a[2][2]-l[2][0]**2-l[2][1]**2)
    
    l[3][2] = (a[3][2]-l[3][0]*l[2][0]-l[3][1]*l[2][1])/l[2][2]
    
    l[3][3] = np.sqrt(a[3][3]-l[3][0]**2-l[3][1]**2-l[3][2]**2)
    
    return l

In [6]:
l = choleskydecomp4(a)
print ("L = ",l)

L =  [[ 2.          0.          0.          0.        ]
 [ 0.5         1.6583124   0.          0.        ]
 [ 0.5        -0.75377836  1.08711461  0.        ]
 [ 0.5         0.45226702  0.0836242   1.24034735]]


In [11]:
import scipy.linalg

a = np.array([[4,1,1,1],[1,3,-1,-1],[1,-1,2,0],[1,1,0,2]])

l = scipy.linalg.cholesky(a,lower=True)

print ("L = ",l)

L =  [[ 2.          0.          0.          0.        ]
 [ 0.5         1.6583124   0.          0.        ]
 [ 0.5        -0.75377836  1.08711461  0.        ]
 [ 0.5         0.45226702  0.0836242   1.24034735]]
