In [1]:
import numpy as np
import scipy.linalg

In [2]:
A = np.array([[58.9,0.03],[-6.10,5.31]])

In [3]:
a = A[0][0]
b = A[0][1]
c = A[1][0]
d = A[1][1]

In [4]:
detA = a*d - b*c

if detA == 0:
    print ("Singular!!!!")
else:
    print ("Non-Singular")

Non-Singular


In [5]:
A_inf = max(abs(a)+abs(b),abs(c)+abs(d))
print ("A_inf = ",A_inf)

print ("A_inf (numpy) = ",np.linalg.norm(A,np.inf))

A_inf =  58.93
A_inf (numpy) =  58.93


In [6]:
Ainv = 1.0/detA*np.array([[d,-b],[-c,a]])
print (Ainv)

[[ 1.69680005e-02 -9.58644094e-05]
 [ 1.94924299e-02  1.88213790e-01]]


In [7]:
Ainv_inf = max(abs(Ainv[0][0])+abs(Ainv[0,1]),abs(Ainv[1][0])+abs(Ainv[1,1]))
print ("Ainv_inf = ",Ainv_inf)

print ("A_inf (scipy) = ",np.linalg.norm(Ainv,np.inf))

Ainv_inf =  0.20770622032197664
A_inf (scipy) =  0.20770622032197664


In [8]:
K = A_inf*Ainv_inf
print ("K = ",K)

print ("K (numpy) = ",np.linalg.cond(A,np.inf))

K =  12.240127563574083
K (numpy) =  12.240127563574081


In [9]:
B = np.array([59.2,47.0]).transpose()

In [10]:
x_exact = np.array([1,10]).transpose()
x_approx = np.array([1.02,9.98]).transpose()

In [11]:
x_diff = x_exact - x_approx
print (np.linalg.norm(x_diff,np.inf))

0.020000000000000018


In [12]:
Numerator = B - np.dot(A,x_approx)

print (A)
print (x_approx)
print (np.dot(A,x_approx))

[[ 5.89e+01  3.00e-02]
 [-6.10e+00  5.31e+00]]
[1.02 9.98]
[60.3774 46.7718]


In [13]:
print (Numerator)

[-1.1774  0.2282]


In [14]:
print (np.linalg.cond(A,np.inf)*np.linalg.norm(Numerator,np.inf)/np.linalg.norm(A,np.inf))

0.24455330380709497


In [15]:
Numerator = B - np.dot(A,x_exact)

print (A)
print (x_exact)
print (np.dot(A,x_exact))

[[ 5.89e+01  3.00e-02]
 [-6.10e+00  5.31e+00]]
[ 1 10]
[59.2 47. ]


In [16]:
print (Numerator)

[7.10542736e-15 7.10542736e-15]


In [17]:
print (np.linalg.cond(A,np.inf)*np.linalg.norm(Numerator,np.inf)/np.linalg.norm(A,np.inf))

1.4758414602196738e-15
