In [1]:
import numpy as np
import math

def round_to_n(x,n):
    for i in range(len(x)):
        if x[i] == 0:
            continue
        else:
            x[i] = round(x[i], -int(math.floor(math.log10(abs(x[i])))) + (n - 1))
    return x

In [2]:
r1 = np.array([3.3330,15920,10.333,7953])
r2 = np.array([2.2220,16.710,9.612,0.965])
r3 = np.array([-1.5611,5.1792,-1.6855,2.714])

d = 6

In [3]:
r1 = round_to_n(r1,d)
r2 = round_to_n(r2,d)
r3 = round_to_n(r3,d)
print (r1)
print (r2)
print (r3)

[3.3330e+00 1.5920e+04 1.0333e+01 7.9530e+03]
[ 2.222 16.71   9.612  0.965]
[-1.5611  5.1792 -1.6855  2.714 ]


In [4]:
r2 = r2 - r1*r2[0]/r1[0]
r3 = r3 - r1*r3[0]/r1[0]
r1 = round_to_n(r1,d)
r2 = round_to_n(r2,d)
r3 = round_to_n(r3,d)

In [5]:
print (r1)
print (r2)
print (r3)

[3.3330e+00 1.5920e+04 1.0333e+01 7.9530e+03]
[ 0.00000e+00 -1.05966e+04  2.72333e+00 -5.30103e+03]
[0.00000e+00 7.46174e+03 3.15424e+00 3.72771e+03]


In [6]:
r3 = r3 - r2*r3[1]/r2[1]
r1 = round_to_n(r1,d)
r2 = round_to_n(r2,d)
r3 = round_to_n(r3,d)

In [7]:
print (r1)
print (r2)
print (r3)

[3.3330e+00 1.5920e+04 1.0333e+01 7.9530e+03]
[ 0.00000e+00 -1.05966e+04  2.72333e+00 -5.30103e+03]
[ 0.00000e+00 -9.09495e-13  5.07191e+00 -5.08237e+00]


In [8]:
r1 = r1 - r2*r1[1]/r2[1]
r2 = r2 - r3*r2[2]/r3[2]
r1 = round_to_n(r1,d)
r2 = round_to_n(r2,d)
r3 = round_to_n(r3,d)

In [9]:
print (r1)
print (r2)
print (r3)

[  3.333    0.      14.4244 -11.1015]
[     0.  -10596.6      0.   -5298.3]
[ 0.00000e+00 -9.09495e-13  5.07191e+00 -5.08237e+00]


In [10]:
r1 = r1 - r3*r1[2]/r3[2]
r1 = round_to_n(r1,d)
r2 = round_to_n(r2,d)
r3 = round_to_n(r3,d)

In [11]:
print (r1)
print (r2)
print (r3)

[3.33300e+00 2.58658e-12 0.00000e+00 3.35265e+00]
[     0.  -10596.6      0.   -5298.3]
[ 0.00000e+00 -9.09495e-13  5.07191e+00 -5.08237e+00]


In [12]:
r1 = r1/r1[0]
r2 = r2/r2[1]
r3 = r3/r3[2]
r1 = round_to_n(r1,d)
r2 = round_to_n(r2,d)
r3 = round_to_n(r3,d)

In [13]:
print (r1)
print (r2)
print (r3)

[1.00000e+00 7.76052e-13 0.00000e+00 1.00590e+00]
[-0.   1.  -0.   0.5]
[ 0.00000e+00 -1.79320e-13  1.00000e+00 -1.00206e+00]


In [14]:
x3 = r3[3]/r3[2]
x2 = (r2[3] - r2[2]*x3)/r2[1]
x1 = (r1[3] - r1[2]*x3 - r1[1]*x2)/r1[0]

print (x1,x2,x3)

1.0058999999996119 0.5 -1.00206
