In [19]:
import numpy as np
import scipy.linalg

In [20]:
A = np.array([[58.9,0.03],[-6.10,5.31]])

In [21]:
a = A[0][0]
b = A[0][1]
c = A[1][0]
d = A[1][1]

In [22]:
detA = a*d - b*c

if detA == 0:
    print ("Singular!!!!")
else:
    print ("Non-Singular")

Non-Singular


In [31]:
A_inf = max(abs(a)+abs(b),abs(c)+abs(d))
print ("A_inf = ",A_inf)

print ("A_inf (numpy) = ",np.linalg.norm(A,np.inf))

A_inf =  58.93
A_inf (scipy) =  58.93


In [9]:
Ainv = 1.0/detA*np.array([[d,-b],[-c,a]])
print (Ainv)

[[ 1.69680005e-02 -9.58644094e-05]
 [ 1.94924299e-02  1.88213790e-01]]


In [32]:
Ainv_inf = max(abs(Ainv[0][0])+abs(Ainv[0,1]),abs(Ainv[1][0])+abs(Ainv[1,1]))
print ("Ainv_inf = ",Ainv_inf)

print ("A_inf (scipy) = ",np.linalg.norm(Ainv,np.inf))

Ainv_inf =  0.20770622032197664
A_inf (scipy) =  0.20770622032197664


In [30]:
K = A_inf*Ainv_inf
print ("K = ",K)

print ("K (numpy) = ",np.linalg.cond(A,np.inf))

K =  12.240127563574083
K (numpy) =  12.240127563574081


In [45]:
B = np.array([59.2,47.0]).transpose()

In [68]:
x_exact = np.array([1,10]).transpose()
x_approx = np.array([1.02,9.98]).transpose()

In [64]:
x_diff = x_exact - x_approx
print (np.linalg.norm(x_diff,np.inf))

0.0009999999999998899


In [65]:
Numerator = B - np.dot(A,x_approx)

print (A)
print (x_approx)
print (np.dot(A,x_approx))

[[ 5.89e+01  3.00e-02]
 [-6.10e+00  5.31e+00]]
[1.001 9.999]
[59.25887 46.98859]


In [66]:
print (Numerator)

[-0.05887  0.01141]


In [67]:
print (np.linalg.cond(A,np.inf)*np.linalg.norm(Numerator,np.inf)/np.linalg.norm(A,np.inf))

0.012227665190353051


In [54]:
Numerator = B - np.dot(A,x_exact)

print (A)
print (x_exact)
print (np.dot(A,x_exact))

[[ 5.89e+01  3.00e-02]
 [-6.10e+00  5.31e+00]]
[ 1 10]
[59.2 47. ]


In [55]:
print (Numerator)

[7.10542736e-15 7.10542736e-15]


In [56]:
print (np.linalg.cond(A,np.inf)*np.linalg.norm(Numerator,np.inf)/np.linalg.norm(A,np.inf))

1.4758414602196738e-15
