In [1]:
import numpy as np
import scipy.linalg

In [25]:
debug = True
n = 5

H = np.zeros(n*n)
H = H.reshape(n,n)

for i in range(n):
    for j in range(n):
        # Remember that array indices go from 0 to n-1 !!!!
        H[i][j] = 1/(i+j+1)
        
if (debug): print (H)

[[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]


In [23]:
x = np.ones(n).transpose()
b = np.dot(H,x).transpose()

print (x)
print (b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3.59773966 2.6453587  2.19081325 1.90095818 1.69262484 1.53262484
 1.40441972 1.29859961 1.2093139  1.13268554 1.06601888 1.00736785
 0.95528452 0.90866447 0.86664766 0.82855243 0.7938302  0.7620337
 0.73279394 0.70580338]


In [24]:
try:
    # conclusion: don't ever use this!!!!
    xstar = np.linalg.solve(H,b)
    print ("Solution: ",xstar)
    error = x - xstar
    residual = b - np.dot(H,xstar)
    print ("Error: ", error)
    print ("Residual: ",residual)
except:
    print ("Singular matrix!")

Solution:  [ 1.00000012  0.99998138  1.00070022  0.98867414  1.0970538   0.51540766
  2.4586396  -1.59697364  3.49819723 -0.19820929  2.33122282 -1.77118347
  3.17448568 -1.47732467  8.33808017 -6.83575271 -0.3942067   9.30102144
 -4.73440098  2.30458727]
Error:  [-1.22700525e-07  1.86194451e-05 -7.00222212e-04  1.13258585e-02
 -9.70537970e-02  4.84592339e-01 -1.45863960e+00  2.59697364e+00
 -2.49819723e+00  1.19820929e+00 -1.33122282e+00  2.77118347e+00
 -2.17448568e+00  2.47732467e+00 -7.33808017e+00  7.83575271e+00
  1.39420670e+00 -8.30102144e+00  5.73440098e+00 -1.30458727e+00]
Residual:  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.22044605e-16
  4.44089210e-16  2.22044605e-16  0.00000000e+00  2.22044605e-16
  2.22044605e-16 -2.22044605e-16  0.00000000e+00 -2.22044605e-16
  2.22044605e-16  2.22044605e-16  1.11022302e-16  0.00000000e+00
  1.11022302e-16 -1.11022302e-16  2.22044605e-16  0.00000000e+00]


In [18]:
epsilon = 1E-8

if (abs(residual[2]) < epsilon):
    print ("All is well!")
else:
    print ("WTF?")

All is well!
