In [1]:
import numpy as np
import math

def round_to_n(x,n):
    for i in range(len(x)):
        if x[i] == 0:
            continue
        else:
            x[i] = round(x[i], -int(math.floor(math.log10(abs(x[i])))) + (n - 1))
    return x

In [2]:
r1 = np.array([3.3330,15920,10.333,7953])
r2 = np.array([2.2220,16.710,9.612,0.965])
r3 = np.array([-1.5611,5.1792,-1.6855,2.714])

d = 5

In [3]:
r1 = round_to_n(r1,d)
r2 = round_to_n(r2,d)
r3 = round_to_n(r3,d)
print (r1)
print (r2)
print (r3)

[3.3330e+00 1.5920e+04 1.0333e+01 7.9530e+03]
[ 2.222 16.71   9.612  0.965]
[-1.5611  5.1792 -1.6855  2.714 ]


In [4]:
r2 = r2 - r1*r2[0]/r1[0]
r3 = r3 - r1*r3[0]/r1[0]
r1 = round_to_n(r1,d)
r2 = round_to_n(r2,d)
r3 = round_to_n(r3,d)

In [5]:
print (r1)
print (r2)
print (r3)

[3.3330e+00 1.5920e+04 1.0333e+01 7.9530e+03]
[ 0.0000e+00 -1.0597e+04  2.7233e+00 -5.3010e+03]
[0.0000e+00 7.4617e+03 3.1542e+00 3.7277e+03]


In [6]:
dummy = r2
r2 = r3
r3 = dummy
print (r1)
print (r2)
print (r3)

[3.3330e+00 1.5920e+04 1.0333e+01 7.9530e+03]
[0.0000e+00 7.4617e+03 3.1542e+00 3.7277e+03]
[ 0.0000e+00 -1.0597e+04  2.7233e+00 -5.3010e+03]


In [7]:
r3 = r3 - r2*r3[1]/r2[1]
r1 = round_to_n(r1,d)
r2 = round_to_n(r2,d)
r3 = round_to_n(r3,d)

In [8]:
print (r1)
print (r2)
print (r3)

[3.3330e+00 1.5920e+04 1.0333e+01 7.9530e+03]
[0.0000e+00 7.4617e+03 3.1542e+00 3.7277e+03]
[ 0.0000e+00 -1.8190e-12  7.2028e+00 -6.9736e+00]


In [9]:
x3 = r3[3]/r3[2]
x2 = (r2[3] - r2[2]*x3)/r2[1]
x1 = (r1[3] - r1[2]*x3 - r1[1]*x2)/r1[0]

print (x1,x2,x3)

0.9629096876505236 0.49998711156072323 -0.9681790414838675
