In [1]:
import numpy as np

In [2]:
r1 = np.array([3.3330,15920,10.333,7953])
r2 = np.array([2.2220,16.710,9.612,0.965])
r3 = np.array([-1.5611,5.1792,-1.6855,2.714])

d = 5

In [3]:
r1 = r1.round(decimals=d)
r2 = r2.round(decimals=d)
r3 = r3.round(decimals=d)
print (r1)
print (r2)
print (r3)

[3.3330e+00 1.5920e+04 1.0333e+01 7.9530e+03]
[ 2.222 16.71   9.612  0.965]
[-1.5611  5.1792 -1.6855  2.714 ]


In [4]:
r1 = r1/r1[0]
r2 = r2/r2[0]
r3 = r3/r3[0]
r1 = r1.round(decimals=d)
r2 = r2.round(decimals=d)
r3 = r3.round(decimals=d)

In [5]:
print (r1)
print (r2)
print (r3)

[1.00000000e+00 4.77647765e+03 3.10021000e+00 2.38613861e+03]
[1.      7.52025 4.32583 0.43429]
[ 1.      -3.31766  1.07969 -1.73852]


In [6]:
r2 = r2 - r1
r3 = r3 - r1
r2 = r2/r2[1]
r3 = r3/r3[1]
r1 = r1.round(decimals=d)
r2 = r2.round(decimals=d)
r3 = r3.round(decimals=d)

In [7]:
print (r1)
print (r2)
print (r3)

[1.00000000e+00 4.77647765e+03 3.10021000e+00 2.38613861e+03]
[-0.0000e+00  1.0000e+00 -2.6000e-04  5.0026e-01]
[-0.0000e+00  1.0000e+00  4.2000e-04  4.9958e-01]


In [8]:
r3 = r3 - r2
if (not(r3[2]==0)):
    r3 = r3/r3[2]
r1 = r1.round(decimals=d)
r2 = r2.round(decimals=d)
r3 = r3.round(decimals=d)

In [9]:
print (r1)
print (r2)
print (r3)

[1.00000000e+00 4.77647765e+03 3.10021000e+00 2.38613861e+03]
[-0.0000e+00  1.0000e+00 -2.6000e-04  5.0026e-01]
[ 0.  0.  1. -1.]


In [10]:
if (not(r2[1]==0)):
    r1 = r1 - r1[1]/r2[1]*r2
r1 = r1.round(decimals=d)
r2 = r2.round(decimals=d)
r3 = r3.round(decimals=d)

In [11]:
print (r1)
print (r2)
print (r3)

[ 1.       0.       4.34209 -3.3421 ]
[-0.0000e+00  1.0000e+00 -2.6000e-04  5.0026e-01]
[ 0.  0.  1. -1.]


In [12]:
if (not(r3[2]==0)):
    r1 = r1 - r1[2]/r3[2]*r3
r1 = r1.round(decimals=d)
r2 = r2.round(decimals=d)
r3 = r3.round(decimals=d)

In [13]:
print (r1)
print (r2)
print (r3)

[1.      0.      0.      0.99999]
[-0.0000e+00  1.0000e+00 -2.6000e-04  5.0026e-01]
[ 0.  0.  1. -1.]


In [14]:
if (not(r3[2]==0)):
    r2 = r2 - r2[2]/r3[2]*r3
r1 = r1.round(decimals=d)
r2 = r2.round(decimals=d)
r3 = r3.round(decimals=d)

In [15]:
print (r1)
print (r2)
print (r3)

[1.      0.      0.      0.99999]
[0.  1.  0.  0.5]
[ 0.  0.  1. -1.]
