In [76]:
import numpy as np
import math

def round_to_n(x,n):
    for i in range(len(x)):
        for j in range(len(x)+1):
            if x[i][j] == 0:
                continue
            else:
                x[i][j] = round(x[i][j], -int(math.floor(math.log10(abs(x[i][j])))) + (n - 1))
    return x

def elim(A,row,row1,row2,position,d):
    factor = A[row1-1][position-1]/A[row2-1][position-1]
    for i in range(len(A)+1):
        A[row-1][i] = A[row1-1][i] - A[row2-1][i]*factor
    A = round_to_n(A,d)
    return A

def norm(A,row,pos,d):
    factor = A[row-1][pos-1]
    for i in range(len(A)+1):
        A[row-1][i] = A[row-1][i]/factor
    A = round_to_n(A,d)
    return A

In [77]:
n = 3
m = n + 1
A = np.array([[3.3330,15920,10.333,7953],[2.2220,16.710,9.612,0.965],[-1.5611,5.1792,-1.6855,2.714]])

d = 3

In [78]:
A = round_to_n(A,d)
print (A)

[[ 3.33e+00  1.59e+04  1.03e+01  7.95e+03]
 [ 2.22e+00  1.67e+01  9.61e+00  9.65e-01]
 [-1.56e+00  5.18e+00 -1.69e+00  2.71e+00]]


In [79]:
# r2 = r2 - r1*r2[0]/r1[0]
A = elim(A,2,2,1,1,d)

# r3 = r3 - r1*r3[0]/r1[0]
A = elim(A,3,3,1,1,d)


In [80]:
print (A)

[[ 3.33e+00  1.59e+04  1.03e+01  7.95e+03]
 [ 0.00e+00 -1.06e+04  2.74e+00 -5.30e+03]
 [ 0.00e+00  7.45e+03  3.14e+00  3.73e+03]]


In [81]:
#r3 = r3 - r2*r3[1]/r2[1]
A = elim(A,3,3,2,2,d)

In [82]:
print (A)

[[ 3.33e+00  1.59e+04  1.03e+01  7.95e+03]
 [ 0.00e+00 -1.06e+04  2.74e+00 -5.30e+03]
 [ 0.00e+00  0.00e+00  5.07e+00  5.00e+00]]


In [83]:
#r1 = r1 - r2*r1[1]/r2[1]
A = elim(A,1,1,2,2,d)

#r2 = r2 - r3*r2[2]/r3[2]
A = elim(A,2,2,3,3,d)

In [84]:
print (A)

[[ 3.33e+00  0.00e+00  1.44e+01  0.00e+00]
 [ 0.00e+00 -1.06e+04  0.00e+00 -5.30e+03]
 [ 0.00e+00  0.00e+00  5.07e+00  5.00e+00]]


In [85]:
#r1 = r1 - r3*r1[2]/r3[2]
A = elim(A,1,1,3,3,d)

In [86]:
print (A)

[[ 3.33e+00  0.00e+00  0.00e+00 -1.42e+01]
 [ 0.00e+00 -1.06e+04  0.00e+00 -5.30e+03]
 [ 0.00e+00  0.00e+00  5.07e+00  5.00e+00]]


In [87]:
A = norm(A,1,1,d)
A = norm(A,2,2,d)
A = norm(A,3,3,d)

print (A)

[[ 1.     0.     0.    -4.26 ]
 [-0.     1.    -0.     0.5  ]
 [ 0.     0.     1.     0.986]]
